source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!

target 'XLForm' do

pod 'XLForm', :git => 'https://github.com/patriciamontalvo/XLForm.git', :branch => 'TypeFloatLabeled'

#Following pods are used for custom row examples
pod 'AFNetworking', '~> 2.0', :inhibit_warnings => true
pod 'XLData', :git => 'https://github.com/xmartlabs/XLData.git', :commit => '1f9019b56242a2019c7f7e11ec4ef823c397ebcf', :inhibit_warnings => true
pod 'JVFloatLabeledTextField', '1.0.2', :inhibit_warnings => true
pod 'AXRatingView', '1.0.3', :inhibit_warnings => true
pod 'SHSPhoneComponent'
pod 'ARAutocompleteTextView', :git => 'https://github.com/patriciamontalvo/ARAutocompleteTextView.git'
 pod 'AMPopTip','~>1.0.3'
end
